name: Deploy
run-name: Deploy ${{ github.ref_name }} to production by @${{ github.actor }}

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        with:
          sparse-checkout: ci/ssh

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          rsync -vr ci/ssh/ ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod -R u=rwX,g=,o= ~/.ssh

      - name: Build on Vulcan
        run: ssh vulcan nix build "github:${{ github.repository }}/${{ github.sha }}"

      - name: Deploy on Vulcan
        run: ssh vulcan home-manager switch --flake "github:${{ github.repository }}/${{ github.sha }}"
